// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Entrega
{
    public int IdEntrega { get; set; }

    public int? IdRuta { get; set; }

    public int? IdPedido { get; set; }

    public DateTime? HoraEntrega { get; set; }

    public string EstadoEntrega { get; set; }

    public virtual Pedido IdPedidoNavigation { get; set; }

    public virtual Ruta IdRutaNavigation { get; set; }
}