// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Pedido
{
    public int IdPedido { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdCliente { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual Cliente IdClienteNavigation { get; set; }
}