// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Rol
{
    public int IdRol { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}