// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Ruta
{
    public int IdRuta { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdUsuario { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual Usuario IdUsuarioNavigation { get; set; }
}