// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Ubicacion
{
    public int IdUbicacion { get; set; }

    public int? IdCliente { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public string Direccion { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }
}