// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int? IdRol { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual ICollection<Ruta> Ruta { get; set; } = new List<Ruta>();
}